DROP TABLE IF EXISTS VETERINARIOS;
CREATE TABLE VETERINARIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
    numero_licencia VARCHAR(50) NOT NULL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    especialidad VARCHAR(100) NOT NULL
);

INSERT INTO VETERINARIOS
VALUES (121215, 'OSCAR', 'RODRIGUEZ','ORTODPEDISTA'),
(151533, 'MARIO', 'MEDINA','GASTROENTEROLOGO'),
(151533, 'ALEJANDRO', 'RIOS','VETERINARIO'),
(151533, 'FELIPE', 'RESTREPO','FISIOTERAPEUTA');
